unit UCommands;

interface

const
  CMD_BASE = 100;

  CMD_CON_ALL_SHUTDOWN = CMD_BASE + 1;

  CMD_CON_ALL_WHOAREYOU = CMD_BASE + 2;

  CMD_MOC_CON_WHOIAM = CMD_BASE + 3;
  CMD_MON_CON_WHOIAM = CMD_BASE + 4;

  CMD_CON_MOC_GET_INFO_PORT = CMD_BASE + 5;
  CMD_MOC_CON_INFO_PORT = CMD_BASE + 6;

  CMD_CON_MON_CONNECTION_MON_TO_MOC = CMD_BASE + 7;
  CMD_CON_MON_RESTART = CMD_BASE + 8;
  CMD_MON_CON_CAST_STATUS = CMD_BASE + 9;

  CMD_MOC_CON_PING = CMD_BASE + 10;
  CMD_MON_CON_PING = CMD_BASE + 11;
  CMD_CON_MOC_PING = CMD_BASE + 12;
  CMD_CON_MON_PING = CMD_BASE + 13;
  CMD_PING_REPLY = CMD_BASE + 14;

//  CMD_CON_MON_GET_INFO = CMD_BASE + 8;
//  CMD_MON_CON_INFO = CMD_BASE + 9;
//
//  CMD_CON_MOC_GET_INFO = CMD_BASE + 10;
//  CMD_MOC_CON_INFO = CMD_BASE + 11;
//
//  CMD_CON_MOC_GET_SCREENSHOT = CMD_BASE + 12;
//  CMD_MOC_CON_SCREENSHOT = CMD_BASE + 13;
//
//  CMD_MOC_MON_GET_IDENTITY = CMD_BASE + 14;
//  CMD_MON_MOC_IDENTITY = CMD_BASE + 15;
//
//  CMD_MOC_MON_UPDATE_CAST = CMD_BASE + 16;
//
//  CMD_CON_MOC_CAST_INFO = CMD_BASE + 17;
//  CMD_CON_MON_CAST_INFO = CMD_BASE + 18;


implementation

end.
