object frmPopChat: TfrmPopChat
  Left = 0
  Top = 0
  BorderStyle = bsNone
  ClientHeight = 82
  ClientWidth = 351
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object Panel1: TPanel
    Left = -1
    Top = -1
    Width = 628
    Height = 328
    Color = 5981737
    ParentBackground = False
    TabOrder = 0
    object lblSender: TLabel
      Left = 22
      Top = 6
      Width = 43
      Height = 17
      Alignment = taCenter
      Caption = 'Sender'
      Font.Charset = ANSI_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Jefferies'
      Font.Style = []
      ParentFont = False
    end
    object lblMessage: TLabel
      Left = 22
      Top = 35
      Width = 59
      Height = 19
      Alignment = taCenter
      Caption = 'Message'
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWhite
      Font.Height = -16
      Font.Name = 'Tahoma'
      Font.Style = []
      ParentFont = False
    end
    object btnOpen: TButton
      Left = 267
      Top = 53
      Width = 75
      Height = 25
      Caption = 'Open'
      TabOrder = 0
      Visible = False
      OnClick = btnOpenClick
    end
  end
  object Timer1: TTimer
    OnTimer = Timer1Timer
    Left = 147
    Top = 14
  end
end
